# Docker Compsoe
# - 여러 개의 컨테이너들을 동시에 실행시키고 관리
# - 컨테이너 실행 명령어들을 한번에 관리
# - 컨테이너 간 네트워크 설정
# - 도커 컴포즈에서 실행되는 컨테이너들은 자동으로 하나의 네트워크에서 실행됨
# - 데이터를 영구적으로 보관할 수 있는 volume도 자동적으로 생성되고 연결됨
# - services: 도커 컴포즈에서 실행되는 하나의 프로그램 단위, 컨테이너를 어떤 식으로 실행할 지에 대한 일종의 가이드라인
# - depends_on: 몇몇 서비스는 선행되는 서비스가 있어야 정상적으로 실행될 수 있음. 이때 depends_on을 설정해주면 컨테이너의 실행 순서를 제어 가능

services:
  webserver:
    image: hello:latest
    container_name: hello-container
    ports:
      - 3000:3000
    depends_on:
      - db
  nginx:
    image: nginx:1
    container_name: nginx-container
    ports:
      - 80:80
  db:
    image: postgres:17-alpine
    container_name: db-container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
